version: "3.9"
services:
  api:
    build: .
    environment:
      DB_PASSWORD: <YOUR_PASSWORD>
      DOMAIN: https://example.com || http://localhost:8889
    ports:
      - "127.0.0.1:8889:8000"
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: <YOUR_PASSWORD>
      POSTGRES_DB: p2p
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - my-network

networks:
  my-network:

volumes:
  db-data:
